### ISSUE TITLE
Linear layer state['step'] increament is 2

### ISSUE THREAD

**Issue by civerjia** [zeke-xie/adaptive-inertia-adai#3]
If I define a simple linear model like this:
```
class TinyModel(torch.nn.Module):

    def __init__(self):
        super(TinyModel, self).__init__()

        self.layer1 = torch.nn.Linear(1000, 100, bias=True)
        self.relu = torch.nn.ReLU()

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        return x
```
Linear layer has two parameters, y=xA' +b.
In your adai.py code, state['step'] will be 1 for A, and 2 for b. If we unroll the for loop:
```
param_size = param_size +sizeA
grad = p.grad.data# A's grad
bias_correction2 = 1 - beta2
exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
exp_avg_sq_hat_sum += exp_avg_sq.sum() / bias_correction2

param_size = param_size +sizeb
grad = p.grad.data# b's grad
bias_correction2 = 1 - beta2**2
exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
exp_avg_sq_hat_sum += exp_avg_sq.sum() / bias_correction2

```

Is it a bug for a layer with multiple parameters?

**Comment by zeke-xie** [comment]
Hi civerjia,

If I understand your question correctly, state['step'] will be 1 for both A and b. 

Because every time we enter a new loop, the state is defined as "state = self.state[p]" again. 
Thus, state[A] and state[b] are two things.

The "state" is actually defined similarly to the state in standard Adam of PyTorch 1.4.0.

Please see
https://pytorch.org/docs/1.4.0/_modules/torch/optim/adam.html#Adam

**Comment by civerjia** [comment]
You are right, thanks
